[package]
name = "sp1"
version = "0.3.0"
edition = "2021"
resolver = "2"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
lazy_static = { workspace = true }

[build-dependencies]
sp1-build = { version = "3", default-features = false }


[features]
bench = []